# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b363f55f84d85b36c717af1c2ffeb21670200da61b4cf23dc25c4de9813d8956f2e39f4ec133a77e337d637725cb9a2c9079313d6a6f3c4b6f3d0dd419e64c5

test:
  secret_key_base: bf27518ae9a8b4781d5cddf24a78ffcfd9117305acaa6b94f86b8a211b4fa44b3a7c60cdbd6a60028bae2dd88d0b3aa227d5d3dbdacb2a68685413a6b0a6b4d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
